version: '2'

networks:
  kafka-test:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.5
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-test
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: bitnami/kafka:2.3.0
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - kafka-test
    ports:
      - "9092:9092"
